### ISSUE TITLE
current ISO outdated

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-mklive#101]
Hi,

The current ISO images in the repository seems to be **outdated**.

We can't do a **clean net-installation** with them because of a PAM problem...

It is necessary to build a new set of ISO images to put in the current repository.

Regards ;)

**Comment by Duncaen** [comment]
Sure, for nearly a year it is not possible to do a "clean net-install".
This is not a problem for the target audience of Void Linux.
And it would be nice if you could really try to make better bug reports next time, this Issues has no informations about the problem, this would make it easier for those that are not aware of this or don't know the conext.

**Comment by xtraeme** [comment]
The issue is that I sign all files and I've been having real life
problems...
I will be back in 2 months max, please be patient.

The `void-mklive` repo can be used to make your own ISOs easily...

Thanks!

**Comment by Gottox** [comment]
@xtraeme We can upload the ISOs by ourselves. But we need to sign them.

**Comment by cr6void** [comment]
@xtraeme I just want to say: I have an **immense respect** for your work. Void is wonderful.

If you need something I will do whatever I can to help you at this difficult moment...

@Duncaen Maybe the "target audience" does not need ISO images, if you say so...
...but **why** should we offer **outdated ISO** on the [Download page](http://www.voidlinux.eu/download/) ??
It doesn't make sense, at least for me. Don't get me wrong ;)

**Comment by masato9000** [comment]
@cr6void perhaps this will help you make some sense of it.

The "outdated" isos are needed to install the system.  The way I always did it was to do a local install of the base system and do a post-install update after booting the system.

In this case, I don't personally see the benefit of a netinstall over a local install + update, since the download isn't any smaller, but some like it as an option (it IS one less step and there could be cases where that's important) and I wouldn't question their preferences here.

I know of this issue because I was playing with the installation recently.  But I've seen enough "images out of date" posts already and had no wish to add to it (I figure the maintainers are all aware of that fact by now... when you have a full plate, you can only eat so much, so fast).

**Comment by masato9000** [comment]
And since it hasn't actually been done here, a clarification of the SPECIFIC issue ("current iso outdated" isn't really a good bug, since that doesn't say ***why that's a problem*** and again, I think everyone's already aware).

**problem**
On a network install, your user doesn't get created, and you end up with a seemingly successful install, but no added user.  I think you might have a problem changing the root password from the installer default too, but since I've been leaving that alone (nonproduction VMs).

Local-media installs are unaffected

**description:**
The part of the installer script that does useradd and password-related changes targeted at the installed system (useradd -r $TARGETDIR) you get a pam related error when you've done a netinstall with the latest packages.

My _layman's_ interepretation is that the useradd and related binaries in the install environment want to use pam modules in the install target, but due to the spread between versions, have become incompatible with each other.  

If instead the installer does those commands in chroot, then they'd succeed (this I've confirmed).  But there's a design decision in there that I know none of the details on, so have no informed opinion.

**Comment by cr6void** [comment]
@masato I don't know **who** is in charge of the [Void's website](http://www.voidlinux.eu/download/), but this person should write clearly:

For the moment you must use these ISO TO DO A LOCAL INSTALLATION ONLY !

Why this information should be **omitted ?**

>  I think you might have a problem changing the root password from the installer default too

**No.** No problem with the root account, only with the normal user account.

**Comment by aeosynth** [comment]
is it possible to have a key usable by all the void core members for signing isos, instead of using @xtraeme's personal key?

**Comment by masato9000** [comment]
A void-keyring of sorts?  (but with a better name... too boring/unoriginal for Void, don't you think?)

**Comment by Gottox** [comment]
We're working on a solution. I suspect that we will have new ISO tomorrow :)

**Comment by cr6void** [comment]
@Gottox Oh yes I can see new the ISO [here...](https://repo.voidlinux.eu/live/20170219/)

Thanks ! Good Job.

**Comment by cr6void** [comment]
Oups... I forgot to **close** this issue. I apologize !!

Regards.
