### ISSUE TITLE
-c ignored

### ISSUE THREAD

**Issue by mrgreen3** [voidlinux/void-mklive#36]
-c <cachedir>      Use this XBPS cache directory (/var/cache/xbps if unset).

Ignores and draws in packages too tmp folder in build directory, old version used to use currently installed packages...

**Comment by xtraeme** [comment]
Nope, your stupid MODIFICATION of void-mklive is outdated and I'm tired of your issues reporting old or unexistent issues in **void-mklive**.

**Comment by mrgreen3** [comment]
Thanks for your reply, I will double check vanilla mklive.... Any changes I have made are minor. As always your responses are friendly and helpful.

**Comment by xtraeme** [comment]
My responses are friendly with people that have been friendly with void and myself.

You were not friendly.

You are a code stealer and people like you are the cancer of FOSS.

**Comment by mrgreen3** [comment]
Thank you very much. If you own code then why does your licence allow others to modify it? If it is not open source then I will stop using it.

**Comment by configX** [comment]
You are way out of line, @xtraeme . Even if you don't agree with his modification there are better ways to express yourself. Also, your software prohibits modification as long as the COPYING file is intact so what's the issue?

**Comment by Gottox** [comment]
Void is @xtraeme baby for quite some years. Please understand, that he's very concerned about these kind of things. @mrgreen3 crossed some lines himself as he actually violated the BSD by removing the license file from his fork of void-mklive.

**Comment by configX** [comment]
@Gottox, I understand this but that kind of behavior is not warranted even in these circumstances. He should not have created open source software if his intent was not to allow others to use it freely. From what I can tell, @mrgreen3 corrected his mistake by adding the license file back so I'm not sure why @xtraeme continues to criticize in a non-constructive manner.

**Comment by thypon** [comment]
If @mrgreen3 knows something about open source, he'd also know how to interact with their community. @xtraeme only expressed what the majority of the community thinks about his projects.

Maybe it's better, the next time you think forking a project is a good idea, to ask people you are getting code for free if maybe they prefer you cooperate with them instead of rebranding the same product, asking for donations without contributing really to the ecosystem you got from.

We are not talking about what is legal and what is not. We are talking about behaviour. @xtreame response was as little as rude as @mrgreen3 forks. Voidlinux **is not** Archlinux: what it's good for a distribution with hundreds of active developers couldn't be good for a distribution like ours.

PS maybe it's not the right place, but i have to ask something to @mrgreen3 ? How could you use Arch name in ArchBang? Do you know that Arch is trademarked? How you relate to trademark rules?

**Comment by configX** [comment]
@thypon, please see my previous response to @Gottox. What's the point of a COPYING file if people who choose to copy will only be chastised by the Void community? Instead of immediately becoming defensive, help others understand how they can best contribute without stepping on any toes. Even though SpringLinux is a rebranding of Void, I see plenty of credit given to Void so it's not like he was hiding this.

**Comment by dominikh** [comment]
Legality and morality are two different issues. Either way, this issue is closed and resolved, and this discussion thereby done. This is a bug tracker. If you disagree with the way the project is managed, either walk away, or discuss it somewhere else (Google Groups).

**Comment by Ypnose** [comment]
@xtraeme doesn't have to justify himself, when people decide to use outdated tools. Reporting issue that was already fixed or not introduced by the upstream project is totally wrong. If you can't fix the bugs you added, then you shouldn't fork a project like this.

And all people here are adults, hence you can keep you "advices" or your moral. Nobody cares…
