### ISSUE TITLE
Installer should support WPA2 full length passwords

### ISSUE THREAD

**Issue by revington** [voidlinux/void-mklive#79]
WPA2-PSK can be up to 63 chars long. The installer did not allow me to write my password. I think this is the relevant code https://github.com/voidlinux/void-mklive/blob/master/installer.sh.in#L791-L794

**Comment by pullmoll** [comment]
The input field width is 50 characters, but the input length is not limited (0)

The parameters are `"prompt" <row> <column> <input field width> <input max. length>`

You can see that e.g. encryption has an input field width of 4, but is actually limited to 3 characters (it can be `wep` or `wpa`. The field width of 4 is to avoid horizontal scrolling after entering the 3rd character.

**Comment by pullmoll** [comment]
I think your issue is that perhaps you want to enter an already hashed password?

Note that the script uses `wpa_passphrase "$ssid" "$pass" > ...` to hash your password and SSID to give the entry in the config file. See `man wpa_passphrase` for the details.

There is currently no way to enter a `raw PSK`.

**Comment by revington** [comment]
Just the plain password. My password has a length of 62 chars. I know, most of the people do not have such a large passphrase.
